app = "taskee"
primary_region = "iad"

[build]

[deploy]
  release_command = "cd backend && npm run migrate"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.checks]]
    path = "/"
    interval = "10s"
    timeout = "2s"

[statics]
  guest_path = "/app/frontend/dist"
  url_prefix = "/"
